# Generated by Django 5.2.6 on 2025-09-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('treatment', models.CharField(choices=[('Consulta General', 'Consulta General'), ('Blanqueamiento Dental', 'Blanqueamiento Dental'), ('Odontología Cosmética', 'Odontología Cosmética'), ('Implantología', 'Implantología'), ('Urgencia', 'Urgencia')], max_length=100)),
                ('specialist', models.CharField(choices=[('Odontología General', 'Odontología General'), ('Odontopediatría', 'Odontopediatría'), ('Ortodoncista', 'Ortodoncista')], max_length=100)),
                ('message', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
